
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 28
#define YY_END_OF_BUFFER 29
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[382] =
    {   0,
        0,    0,    0,    0,    0,    0,    9,    9,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   29,   27,    6,   27,
        7,    9,   11,   10,   27,    5,    1,    3,    4,    2,
       20,   20,   18,   18,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,    0,    7,    9,   10,   10,   14,    8,
       15,   16,   19,   17,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   15,   19,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   12,   13,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   22,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   13,   13,   12,   13,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   13,   13,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   23,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   25,    0,   26,   21,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   24,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   24,   24,
       24,    0,    0,    0,    0,    0,   24,   24,    0,    0,
        0,    0,    0,   24,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   24,   24,   24,   24,    0,   24,    0,
        0,   24,   24,    0,   24,    0,    0,    0,   24,    0,
        0,    0,    0,   24,    0,   24,   24,   24,   24,    0,
       24,   24,   24,    0,    0,   24,   24,   24,    0,   24,
       24,    0,    0,   24,   24,   24,   24,   24,   24,   24,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    5,    5,    5,    8,    9,
       10,   11,    5,   12,    5,    1,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    5,   15,    5,
       16,    5,    1,    5,   17,   18,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       16,    1,    5,    5,   19,    1,   20,   21,   22,   23,

       24,   25,   26,   27,   28,   17,   17,   29,   30,   31,
       32,   33,   17,   34,   35,   36,   37,   38,   17,   39,
       17,   17,   40,    5,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[41] =
    {   0,
        1,    2,    3,    2,    4,    1,    4,    1,    5,    1,
        6,    7,    4,    8,    9,    9,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    4
    } ;

static const flex_int16_t yy_base[410] =
    {   0,
        0,    0,  911,  910,    0,    0,    2,    3,  899,  898,
        1,    2,    9,   13,  897,  896,   15,   17,  901,  900,
      881,   27,   65,    0,  105,    0,  905,  915,  915,   20,
      915,    0,  915,   14,   19,  915,  915,  915,  915,  915,
      915,   22,  915,  891,   34,  871,  144,  884,  864,  868,
        7,  867,    6,   11,  867,  865,  872,  122,  864,  862,
      149,   40,  150,   56,  915,    0,  144,  163,  880,  915,
        0,  915,    0,  915,  173,  868,  857,    0,  872,  852,
      856,  153,  855,  131,  857,  854,  852,  859,  156,  851,
      849,  848,  843,  846,  857,   23,  839,  838,  838,  841,

      836,  840,  844,  837,  842,  166,  159,  160,  191,  195,
      199,  203,  206,  207,  854,  202,    0,    0,  841,  217,
      833,  832,  834,  828,  828,  825,  838,  828,  833,  836,
      225,  829,  826,  819,  821,  815,  813,  817,  820,  824,
      826,  221,  240,  209,  832,  220,  816,  241,  253,  814,
      290,  244,  254,  813,  805,  811,  257,  805,  802,  258,
      295,  261,  915,  310,  262,  802,  796,  807,  802,  802,
      792,  796,  265,  783,  325,  806,  326,  329,  337,  343,
      805,  351,  355,  257,  801,  795,  272,  776,    0,  788,
      763,  760,  207,  752,  744,  745,  739,  735,  742,  268,

      732,  728,  282,    0,  313,  314,  735,  340,  732,  354,
      368,  722,  359,  369,  374,  384,  394,    0,  373,  716,
      385,  725,  725,  710,  388,  712,  389,  714,  731,  397,
      723,  409,  391,  403,  700,  683,  675,  677,  688,  160,
      670,  668,  670,  665,  669,  666,  654,  657,  547,  529,
      224,  413,  515,  416,  419,  423,  429,  915,  444,  459,
      424,  428,  517,  445,  448,  449,  460,  463,  510,  497,
      474,  915,  477,  915,  915,  491,  481,  483,  466,  457,
      447,  451,  445,  437,  464,  428,  415,  408,  405,  393,
      394,  380,  374,  481,  484,  513,  487,  491,  528,    0,

      492,  347,  495,  499,  502,  351,  344,  338,  503,  506,
      507,  321,  313,  303,  289,  284,  514,  517,  284,  273,
      284,  275,  274,  518,  253,  529,  534,  544,  554,    0,
      533,  545,  548,  549,  555,  558,  559,  256,  569,  255,
      240,  570,  573,  211,  574,  215,  202,  185,  577,  184,
      578,  581,  582,  585,  165,  586,  589,  590,  593,  174,
      594,  597,  598,  147,  130,  601,  602,  605,  122,  606,
      609,  124,   39,  610,  613,  614,  617,  618,  621,  622,
      915,  626,  635,  644,  653,  662,  671,  680,  689,  697,
       39,  704,  712,  721,  730,  738,  743,  748,  756,  763,

      771,    9,  779,  788,  796,  803,  811,  819,  827
    } ;

static const flex_int16_t yy_def[410] =
    {   0,
      382,  382,  382,  382,  382,  382,  383,  383,  382,  382,
      384,  384,  385,  385,  386,  386,  387,  387,  382,  382,
      382,  382,  381,   23,  381,   25,  381,  381,  381,  381,
      381,  388,  381,  389,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      390,  391,  392,  381,  381,  388,  389,  389,  393,  381,
      394,  381,  395,  381,  381,  381,  381,   47,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  396,  390,
      391,  392,  397,  392,  393,  393,  394,  395,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      398,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  399,  400,  393,  393,  401,  381,  381,  381,  381,
      398,  151,  151,  381,  381,  381,  402,  381,  381,  151,
      381,  151,  381,  403,  151,  381,  381,  381,  381,  381,
      381,  381,  151,  381,  396,  404,  396,  399,  399,  397,
      405,  400,  400,  401,  401,  401,  401,  381,  149,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  151,  151,  151,  151,  381,  151,  381,  402,
      406,  381,  151,  151,  151,  151,  403,  217,  151,  381,
      151,  381,  381,  381,  402,  381,  151,  381,  404,  404,
      405,  405,  401,  401,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  151,  381,  151,  151,  407,  407,  381,  406,  408,
      151,  151,  381,  151,  151,  151,  402,  402,  381,  381,
      404,  381,  405,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  151,  151,  409,  257,  257,  408,  299,

      151,  381,  151,  151,  402,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  151,  257,  257,  409,  329,
      151,  151,  151,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      151,  151,  151,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
        0,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381
    } ;

static const flex_int16_t yy_nxt[956] =
    {   0,
      381,   30,   31,   30,   33,   33,   37,   37,   37,   37,
      211,   39,   34,   34,   40,   39,   40,   41,   40,   41,
       40,   64,   65,   64,   68,   44,   69,   44,   47,   70,
       47,   71,   72,   95,   73,   75,   98,   75,   96,  100,
      112,  111,   77,  111,   99,   48,   49,   50,   51,   52,
       53,   54,  125,  126,   55,   56,   76,   64,   65,   64,
       57,   58,  377,   59,   60,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   28,   28,   62,   28,   62,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   28,   78,  376,   78,  104,  105,
      109,  113,  109,  113,  381,  375,  381,  106,  373,  109,
      113,   98,   79,   80,   81,   82,   83,   84,   85,   99,
      372,   86,   87,   68,   75,   69,   75,   88,   89,   95,
       90,   91,  104,  105,   96,  136,  138,  140,  141,  280,
      281,  106,  109,  139,  109,   76,  109,  369,  109,  137,

      111,  109,  111,  366,  113,  109,  113,  113,  113,  113,
      113,  365,  145,  113,  146,  364,  113,  113,  148,  145,
      148,  184,  175,  363,  175,  149,  160,  161,  160,  176,
      186,  177,  187,  239,  178,  162,  163,  362,  240,  163,
      163,  180,  148,  180,  148,  205,  360,  205,  181,  149,
      180,  292,  293,  182,  189,  206,  189,  206,  210,  160,
      210,  160,  214,  219,  214,  219,  227,  186,  227,  233,
      358,  190,  191,  192,  193,  194,  195,  196,  357,  355,
      197,  198,  186,  252,  187,  252,  199,  200,  350,  201,
      202,  204,  161,  204,  247,  248,  161,  161,  161,  348,

      162,  163,  347,  249,  163,  163,  163,  346,  345,  163,
      163,  215,  161,  215,  205,  206,  205,  206,  344,  342,
      216,  163,  341,  217,  163,  163,  175,  175,  175,  175,
      175,  340,  175,  176,  176,  177,  177,  176,  175,  177,
      175,  254,  178,  254,  180,  176,  180,  177,  339,  338,
      178,  181,  180,  180,  180,  210,  180,  210,  180,  181,
      262,  180,  262,  181,  182,  180,  334,  333,  182,  256,
      214,  256,  214,  332,  219,  215,  219,  215,  257,  258,
      331,  259,  258,  258,  216,  215,  264,  215,  264,  268,
      227,  268,  227,  325,  216,  215,  161,  215,  271,  271,

      271,  186,  324,  233,  216,  163,  230,  217,  163,  163,
      273,  273,  273,  186,  252,  233,  252,  254,  232,  254,
      295,  323,  295,  274,  256,  301,  256,  301,  322,  262,
      256,  262,  256,  257,  258,  321,  272,  258,  258,  257,
      258,  320,  319,  258,  258,  256,  264,  256,  264,  303,
      304,  303,  304,  318,  257,  258,  316,  259,  258,  258,
      297,  305,  297,  305,  268,  317,  268,  317,  315,  298,
      258,  314,  299,  258,  258,  271,  271,  271,  273,  273,
      273,  313,  326,  230,  326,  295,  232,  295,  297,  312,
      297,  274,  297,  301,  297,  301,  303,  298,  303,  311,

      304,  298,  304,  305,  335,  305,  335,  336,  337,  336,
      337,  310,  309,  272,  327,  317,  327,  317,  343,  349,
      343,  349,  308,  328,  258,  307,  329,  258,  258,  297,
      326,  297,  326,  306,  351,  327,  351,  327,  298,  258,
      302,  299,  258,  258,  328,  327,  352,  327,  352,  353,
      354,  353,  354,  294,  328,  327,  335,  327,  335,  336,
      337,  336,  337,  291,  328,  258,  290,  329,  258,  258,
      356,  359,  356,  359,  343,  361,  343,  361,  349,  351,
      349,  351,  352,  353,  352,  353,  354,  356,  354,  356,
      367,  368,  367,  368,  359,  361,  359,  361,  370,  371,

      370,  371,  374,  367,  374,  367,  368,  370,  368,  370,
      371,  374,  371,  374,  378,  379,  378,  379,  380,  378,
      380,  378,  379,  380,  379,  380,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       66,   66,  289,   66,   66,  288,   66,   66,   66,   67,
       67,  287,   67,   67,   67,   67,   67,   67,  110,  286,

      285,  284,  110,  283,  110,  114,  282,  279,  278,  114,
      277,  114,  115,  115,  276,  115,  115,  115,  115,  115,
      115,  117,  117,  275,  117,  117,  117,  117,  117,  117,
      118,  118,  232,  118,  118,  118,  118,  118,  118,  142,
      230,  270,  269,  142,  143,  267,  266,  265,  143,  164,
      164,  263,  261,  164,  164,  255,  164,  179,  253,  251,
      179,  179,  250,  179,  183,  246,  245,  183,  183,  244,
      183,  185,  185,  243,  185,  185,  185,  185,  185,  185,
      218,  218,  242,  241,  218,  218,  218,  218,  229,  229,
      229,  238,  229,  229,  229,  229,  231,  231,  231,  237,

      231,  231,  231,  231,  260,  236,  235,  234,  260,  260,
      260,  260,  296,  234,  232,  230,  296,  296,  228,  296,
      300,  226,  225,  224,  300,  300,  300,  300,  330,  223,
      222,  221,  330,  330,  330,  330,  220,  213,  212,  209,
      208,  207,  203,  188,  144,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  147,  144,  135,  134,  133,
      132,  131,  130,  129,  128,  127,  124,  123,  122,  121,
      108,  107,  103,  102,  101,  100,   97,   94,   93,   92,
      120,  119,  116,  108,  107,  103,  102,  101,   97,   94,

       93,   92,   77,   74,  381,   46,   45,   45,   42,   42,
       35,   35,   29,   29,   27,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381
    } ;

static const flex_int16_t yy_chk[956] =
    {   0,
        0,    6,    6,    6,    7,    8,   11,   12,   11,   12,
      402,   13,    7,    8,   13,   14,   13,   17,   14,   18,
       14,   30,   30,   30,   34,   17,   34,   18,   22,   35,
       22,   35,   42,   51,   42,   45,   53,   45,   51,   54,
      391,   62,   54,   62,   53,   22,   22,   22,   22,   22,
       22,   22,   96,   96,   22,   22,   45,   64,   64,   64,
       22,   22,  373,   22,   22,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,

       23,   23,   23,   23,   23,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   47,  372,   47,   58,   58,
       61,   63,   61,   63,   67,  369,   67,   58,  365,   61,
       63,   84,   47,   47,   47,   47,   47,   47,   47,   84,
      364,   47,   47,   68,   75,   68,   75,   47,   47,   82,
       47,   47,   89,   89,   82,  106,  107,  108,  108,  240,
      240,   89,  109,  107,  109,   75,  110,  360,  110,  106,

      111,  109,  111,  355,  112,  110,  112,  113,  114,  113,
      114,  350,  116,  112,  116,  348,  113,  114,  120,  144,
      120,  144,  142,  347,  142,  120,  131,  131,  131,  142,
      146,  142,  146,  193,  142,  131,  131,  346,  193,  131,
      131,  143,  148,  143,  148,  152,  344,  152,  143,  148,
      143,  251,  251,  143,  149,  153,  149,  153,  157,  160,
      157,  160,  162,  165,  162,  165,  173,  184,  173,  184,
      341,  149,  149,  149,  149,  149,  149,  149,  340,  338,
      149,  149,  187,  203,  187,  203,  149,  149,  325,  149,
      149,  151,  151,  151,  200,  200,  161,  161,  161,  323,

      151,  151,  322,  200,  151,  151,  161,  321,  320,  161,
      161,  164,  164,  164,  205,  206,  205,  206,  319,  316,
      164,  164,  315,  164,  164,  164,  175,  177,  175,  177,
      178,  314,  178,  175,  177,  175,  177,  178,  179,  178,
      179,  208,  178,  208,  180,  179,  180,  179,  313,  312,
      179,  180,  182,  180,  182,  210,  183,  210,  183,  182,
      213,  182,  213,  183,  182,  183,  308,  307,  183,  211,
      214,  211,  214,  306,  219,  215,  219,  215,  211,  211,
      302,  211,  211,  211,  215,  216,  221,  216,  221,  225,
      227,  225,  227,  293,  216,  217,  217,  217,  230,  230,

      230,  233,  292,  233,  217,  217,  230,  217,  217,  217,
      232,  232,  232,  234,  252,  234,  252,  254,  232,  254,
      255,  291,  255,  232,  256,  261,  256,  261,  290,  262,
      257,  262,  257,  256,  256,  289,  230,  256,  256,  257,
      257,  288,  287,  257,  257,  259,  264,  259,  264,  265,
      266,  265,  266,  286,  259,  259,  284,  259,  259,  259,
      260,  267,  260,  267,  268,  285,  268,  285,  283,  260,
      260,  282,  260,  260,  260,  271,  271,  271,  273,  273,
      273,  281,  294,  271,  294,  295,  273,  295,  297,  280,
      297,  273,  298,  301,  298,  301,  303,  297,  303,  279,

      304,  298,  304,  305,  309,  305,  309,  310,  311,  310,
      311,  278,  277,  271,  296,  317,  296,  317,  318,  324,
      318,  324,  276,  296,  296,  270,  296,  296,  296,  299,
      326,  299,  326,  269,  331,  327,  331,  327,  299,  299,
      263,  299,  299,  299,  327,  328,  332,  328,  332,  333,
      334,  333,  334,  253,  328,  329,  335,  329,  335,  336,
      337,  336,  337,  250,  329,  329,  249,  329,  329,  329,
      339,  342,  339,  342,  343,  345,  343,  345,  349,  351,
      349,  351,  352,  353,  352,  353,  354,  356,  354,  356,
      357,  358,  357,  358,  359,  361,  359,  361,  362,  363,

      362,  363,  366,  367,  366,  367,  368,  370,  368,  370,
      371,  374,  371,  374,  375,  376,  375,  376,  377,  378,
      377,  378,  379,  380,  379,  380,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      388,  388,  248,  388,  388,  247,  388,  388,  388,  389,
      389,  246,  389,  389,  389,  389,  389,  389,  390,  245,

      244,  243,  390,  242,  390,  392,  241,  239,  238,  392,
      237,  392,  393,  393,  236,  393,  393,  393,  393,  393,
      393,  394,  394,  235,  394,  394,  394,  394,  394,  394,
      395,  395,  231,  395,  395,  395,  395,  395,  395,  396,
      229,  228,  226,  396,  397,  224,  223,  222,  397,  398,
      398,  220,  212,  398,  398,  209,  398,  399,  207,  202,
      399,  399,  201,  399,  400,  199,  198,  400,  400,  197,
      400,  401,  401,  196,  401,  401,  401,  401,  401,  401,
      403,  403,  195,  194,  403,  403,  403,  403,  404,  404,
      404,  192,  404,  404,  404,  404,  405,  405,  405,  191,

      405,  405,  405,  405,  406,  190,  188,  186,  406,  406,
      406,  406,  407,  185,  181,  176,  407,  407,  174,  407,
      408,  172,  171,  170,  408,  408,  408,  408,  409,  169,
      168,  167,  409,  409,  409,  409,  166,  159,  158,  156,
      155,  154,  150,  147,  145,  141,  140,  139,  138,  137,
      136,  135,  134,  133,  132,  130,  129,  128,  127,  126,
      125,  124,  123,  122,  121,  119,  115,  105,  104,  103,
      102,  101,  100,   99,   98,   97,   95,   94,   93,   92,
       91,   90,   88,   87,   86,   85,   83,   81,   80,   79,
       77,   76,   69,   60,   59,   57,   56,   55,   52,   50,

       49,   48,   46,   44,   27,   21,   20,   19,   16,   15,
       10,    9,    4,    3,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "main.l"
#line 2 "main.l"
	#include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
	int no_of_comments = 0; 
	int no_of_lines = 0; 
	int no_of_blank_lines = 0;
	int no_of_macros = 0;
    int no_of_variables = 0;
    int no_of_func_dec = 0;
    int no_of_func_def = 0;
    char * temp_string="";
    int flag = 0;
    FILE *temp;
#line 795 "lex.yy.c"
 
#line 797 "lex.yy.c"

#define INITIAL 0
#define count_lines 1
#define count_blank 2
#define count_comment 3
#define count_comment_initial 4
#define remove_string 5
#define remove_string_found 6
#define remove_comment 7
#define remove_comment_found 8
#define count_macro 9
#define count_variable 10
#define count_func_def 11
#define count_func_dec 12

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 21 "main.l"


#line 1032 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 382 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 915 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 23 "main.l"
{BEGIN(remove_string_found);flag = 1; temp_string=temp_string+*yytext;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 24 "main.l"
{BEGIN(remove_string);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 25 "main.l"
;
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 26 "main.l"
{fwrite( yytext, (size_t) yyleng, 1, temp );}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 27 "main.l"
{fwrite( yytext, (size_t) yyleng, 1, temp );}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 29 "main.l"
{no_of_lines++;}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 31 "main.l"
{no_of_blank_lines++;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 33 "main.l"
{BEGIN(count_comment);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 34 "main.l"
;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 35 "main.l"
;
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 36 "main.l"
{no_of_comments++;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 37 "main.l"
BEGIN(count_comment);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 38 "main.l"
{no_of_comments++;BEGIN(count_comment_initial);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 39 "main.l"
{no_of_comments++;BEGIN(count_comment_initial);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 40 "main.l"
{no_of_comments++;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 42 "main.l"
{BEGIN(remove_comment_found);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 43 "main.l"
{BEGIN(remove_comment);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 44 "main.l"
;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 45 "main.l"
;
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 46 "main.l"
{fwrite( yytext, (size_t) yyleng, 1, temp );}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 48 "main.l"
{no_of_macros++;}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 50 "main.l"
no_of_variables++;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 51 "main.l"
no_of_variables++;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 52 "main.l"
no_of_variables++;
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 54 "main.l"
{no_of_func_def++;}
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 56 "main.l"
{no_of_func_dec++;}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 58 "main.l"
;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "main.l"
ECHO;
	YY_BREAK
#line 1240 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(count_lines):
case YY_STATE_EOF(count_blank):
case YY_STATE_EOF(count_comment):
case YY_STATE_EOF(count_comment_initial):
case YY_STATE_EOF(remove_string):
case YY_STATE_EOF(remove_string_found):
case YY_STATE_EOF(remove_comment):
case YY_STATE_EOF(remove_comment_found):
case YY_STATE_EOF(count_macro):
case YY_STATE_EOF(count_variable):
case YY_STATE_EOF(count_func_def):
case YY_STATE_EOF(count_func_dec):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 382 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 382 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 381);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 59 "main.l"


int yywrap(){} 
int main(){ 

    char * original_file="test.c";
	FILE *fp,*out; 

    fp = fopen(original_file,"r");
	yyrestart(fp);
    BEGIN(count_lines);
    yylex(); 
    fclose(fp);

    fp = fopen(original_file,"r");
    yyrestart(fp);
    BEGIN(count_blank);
	yylex(); 
    fclose(fp);

    fp = fopen(original_file,"r");
    temp= fopen("temp_string.c","w"); 
    yyin = fp;
    BEGIN(remove_string);
    yylex(); 
    fclose(fp);
    fclose(temp);

    fp = fopen("temp_string.c","r");
    yyrestart(fp);
    BEGIN(count_comment_initial);
	yylex();

    temp= fopen("temp_comment.c","w"); 
    fp = fopen("temp_string.c","r");
    yyrestart(fp);
    BEGIN(remove_comment);
	yylex();  
    fclose(fp);
    fclose(temp);

    fp = fopen("temp_comment.c","r");
    yyrestart(fp);
    BEGIN(count_macro);
	yylex();  
    fclose(fp);

    fp = fopen("temp_comment.c","r");
    yyrestart(fp);
    BEGIN(count_variable);
	yylex();  
    fclose(fp);

    fp = fopen("temp_comment.c","r");
    yyrestart(fp);
    BEGIN(count_func_def);
	yylex();  
    fclose(fp);

    fp = fopen("temp_comment.c","r");
    yyrestart(fp);
    BEGIN(count_func_dec);
	yylex();  
    fclose(fp);

    remove("temp_comment.c");
    remove("temp_string.c");
    out = fopen("output.txt","w");
	fprintf(out,"\nNumber of comments "
		"in the given input - %d\n", no_of_comments); 
	fprintf(out,"\nNumber of lines "
		"in the given input - %d\n", no_of_lines+1); 
	fprintf(out,"\nNumber of blank lines "
		"in the given input - %d\n", no_of_blank_lines); 
	fprintf(out,"\nNumber of macros "
		"in the given input - %d\n", no_of_macros);
    fprintf(out,"\nNumber of variables "
		"in the given input - %d\n", no_of_variables);  
    fprintf(out,"\nNumber of function definitions "
		"in the given input - %d\n", no_of_func_def);  
    fprintf(out,"\nNumber of function declaration "
		"in the given input - %d\n", no_of_func_dec);
    fclose(out);
	return 0; 
} 
