
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 34
#define YY_END_OF_BUFFER 35
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[401] =
    {   0,
        0,    0,    0,    0,    0,    0,   13,   13,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       35,   33,   10,   33,   11,   13,   15,   14,   33,    9,
        5,    9,    7,    8,    6,   24,   24,   22,   22,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   30,
       31,    3,    3,    0,   11,   13,   14,   14,   18,   12,
       19,    1,    4,   20,   23,   21,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    2,    0,
        0,   19,    4,   23,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   16,   17,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       26,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   17,   17,   16,   17,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   17,   17,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   27,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       29,    0,   32,   25,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   28,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   28,   28,   28,
        0,    0,    0,    0,    0,   28,   28,    0,    0,    0,
        0,    0,   28,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   28,   28,   28,   28,    0,   28,    0,    0,
       28,   28,    0,   28,    0,    0,    0,   28,    0,    0,
        0,    0,   28,    0,   28,   28,   28,   28,    0,   28,
       28,   28,    0,    0,   28,   28,   28,    0,   28,   28,
        0,    0,   28,   28,   28,   28,   28,   28,   28,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    5,    5,    5,    8,    9,
       10,   11,    5,   12,    5,    1,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    5,   15,    5,
       16,    5,    1,    5,   17,   18,   17,   17,   19,   20,
       17,   17,   21,   17,   17,   22,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       16,    1,    5,    5,   23,    1,   24,   25,   26,   27,

       28,   29,   30,   31,   32,   17,   17,   33,   34,   35,
       36,   37,   17,   38,   39,   40,   41,   42,   17,   43,
       17,   17,   44,    5,   45,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[46] =
    {   0,
        1,    2,    3,    2,    4,    1,    4,    1,    5,    1,
        6,    7,    4,    8,    9,    9,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    4,    4
    } ;

static const flex_int16_t yy_base[433] =
    {   0,
        0,    0,  973,  972,    0,    0,    2,    3,  961,  960,
        2,    3,   14,   15,  959,  958,   16,   21,  963,  962,
      939,   31,   73,  118,  163,  208,    0,    2,  956,  955,
      965,  977,  977,   26,  977,    0,  977,   23,   26,  977,
      977,   27,  977,  977,  977,  977,   30,  977,  951,   63,
      927,  252,  941,  943,  919,  923,   17,  922,    7,   16,
      922,  920,  927,   60,  919,  917,   91,   64,   92,  977,
      977,  977,  939,   95,  977,    0,   93,   94,  938,  977,
        0,  977,    0,  977,    0,  977,  108,  922,  911,    0,
      927,  929,  905,  909,   77,  908,   66,  910,  907,  905,

      912,  105,  904,  902,  915,  900,  895,  898,  909,   27,
      891,  890,  890,  893,  888,  892,  896,  889,  894,  114,
      107,   82,  138,  139,  149,  178,  179,  182,  977,  910,
      143,    0,    0,    0,  893,  183,  902,  884,  883,  885,
      879,  879,  876,  889,  879,  884,  887,  293,  880,  877,
      870,  872,  866,  864,  868,  871,  871,  873,  192,  223,
      144,  883,  147,  858,  193,  308,  349,  856,  157,  196,
      224,  855,  845,  849,  227,  843,  840,  231,  243,  234,
      977,  364,  237,  835,  833,  844,  834,  832,  815,  819,
      238,  800,  258,  826,  259,  309,  313,  262,  823,  379,

      380,  237,  819,  816,  238,  791,    0,  807,  781,  783,
       80,  782,  771,  780,  777,  773,  780,  267,  772,  763,
        0,  284,  285,  298,  299,  762,  312,  753,  317,  393,
      737,  324,  340,  352,  399,  409,    0,  341,  728,  353,
      739,  739,  724,  367,  726,  368,  727,  748,  396,  747,
      412,  374,  406,  721,  707,  700,  619,  566,  113,  546,
      536,  539,  530,  534,  535,  526,  523,  526,  499,  172,
      424,  492,  427,  428,  431,  437,  977,  452,  467,  432,
      453,  491,  456,  457,  468,  471,  472,  490,  480,  482,
      977,  485,  977,  977,  476,  469,  465,  452,  443,  438,

      440,  434,  427,  489,  420,  413,  406,  403,  397,  386,
      375,  372,  492,  495,  525,  499,  505,  540,    0,  500,
      354,  504,  520,  521,  359,  349,  341,  526,  529,  530,
      340,  322,  326,  320,  308,  541,  544,  300,  298,  302,
      297,  295,  545,  266,  555,  556,  562,  577,    0,  559,
      578,  581,  582,  592,  593,  596,  264,  597,  255,  247,
      600,  601,  234,  604,  238,  231,  209,  605,  211,  608,
      609,  612,  613,  187,  616,  617,  620,  621,  171,  624,
      625,  628,  163,  155,  629,  632,  633,  106,  636,  637,
       44,    3,  640,  641,  644,  645,  648,  649,  652,  977,

      656,  665,  674,  683,  692,  701,  710,  719,  728,  737,
      746,  754,   10,  761,  769,  778,  787,  796,  804,  809,
      814,  822,  829,  837,    5,  845,  854,  862,  869,  877,
      885,  893
    } ;

static const flex_int16_t yy_def[433] =
    {   0,
      401,  401,  401,  401,  401,  401,  402,  402,  401,  401,
      403,  403,  404,  404,  405,  405,  406,  406,  401,  401,
      401,  401,  407,  407,  408,  408,  401,  401,  409,  409,
      400,  400,  400,  400,  400,  410,  400,  411,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  412,  413,  414,  400,
      400,  400,  400,  400,  400,  410,  411,  411,  415,  400,
      416,  400,  417,  400,  418,  400,  400,  400,  400,   52,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,

      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  419,  412,  413,  414,  420,  414,  400,  415,
      415,  416,  417,  418,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  421,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  422,  423,
      415,  415,  424,  400,  400,  400,  421,  400,  167,  167,
      167,  400,  400,  400,  425,  400,  400,  167,  400,  167,
      400,  426,  167,  400,  400,  400,  400,  400,  400,  400,
      167,  400,  419,  427,  419,  422,  422,  420,  428,  423,

      423,  424,  424,  424,  424,  400,  166,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      167,  167,  167,  167,  167,  400,  167,  400,  425,  429,
      400,  167,  167,  167,  167,  426,  236,  167,  400,  167,
      400,  400,  400,  425,  400,  167,  400,  427,  427,  428,
      428,  424,  424,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      167,  400,  167,  167,  430,  430,  400,  429,  431,  167,
      167,  400,  167,  167,  167,  425,  425,  400,  400,  427,
      400,  428,  400,  400,  400,  400,  400,  400,  400,  400,

      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  167,  167,  432,  430,  430,  431,  318,  167,
      400,  167,  167,  425,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  167,  430,  430,  432,  348,  167,
      167,  167,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  167,
      167,  167,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,    0,

      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400
    } ;

static const flex_int16_t yy_nxt[1023] =
    {   0,
      400,   34,   35,   34,   37,   37,  230,   41,   41,   41,
       41,  126,   38,   38,   42,   42,   44,   44,   46,   45,
       45,   45,   45,   46,  400,  400,   49,   74,   75,   74,
      396,   49,   52,   78,   52,   79,   80,   82,   81,   83,
       84,  112,   85,   70,   71,   70,   71,  109,  114,  113,
       53,   89,  110,   54,   55,   56,   57,   58,   59,   60,
      142,  143,   61,   62,   87,  125,   87,  125,   63,   64,
      395,   65,   66,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   88,
      118,  119,  123,  127,  123,  127,   74,   75,   74,  120,

      112,  123,  127,  400,   78,  400,   79,  109,  113,   87,
      258,   87,  110,  157,  158,  259,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   88,  118,  119,  153,  155,  123,
      123,  123,  123,  394,  120,  156,  299,  300,  123,  123,
      125,  154,  125,  162,  162,  163,  202,  204,  223,  205,
      223,   32,   32,   32,   68,   32,   68,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,  127,
      127,  127,  127,  127,  165,  127,  165,  392,  127,  127,
      391,  166,  127,  193,  165,  193,  165,  224,  388,  224,

      194,  166,  195,  311,  312,  196,   32,   32,   32,   68,
       32,   68,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,  198,  225,  198,  225,  229,  385,
      229,  199,  178,  198,  178,  233,  200,  233,  238,  246,
      238,  246,  384,  383,  179,  179,  179,  204,  204,  252,
      205,   32,   32,   90,  181,   90,  382,  181,  181,  193,
      193,  193,  193,  198,  381,  198,  194,  194,  195,  195,
      199,   91,  198,  379,   92,   93,   94,   95,   96,   97,
       98,  377,  376,   99,  100,  271,  223,  271,  223,  101,
      102,  374,  103,  104,  178,  179,  178,  266,  267,  224,

      225,  224,  225,  180,  181,  369,  268,  181,  181,  207,
      193,  207,  193,  273,  193,  273,  193,  194,  229,  195,
      229,  194,  196,  195,  367,  281,  196,  281,  366,  365,
      208,  209,  210,  211,  212,  213,  214,  364,  363,  215,
      216,  233,  238,  233,  238,  217,  218,  361,  219,  220,
      221,  179,  221,  234,  283,  234,  283,  360,  359,  180,
      181,  358,  235,  181,  181,  234,  179,  234,  287,  246,
      287,  246,  357,  353,  235,  181,  352,  236,  181,  181,
      198,  198,  198,  198,  204,  351,  252,  199,  199,  198,
      198,  350,  200,  200,  275,  344,  275,  290,  290,  290,

      234,  343,  234,  276,  277,  249,  278,  277,  277,  235,
      234,  179,  234,  292,  292,  292,  204,  342,  252,  235,
      181,  251,  236,  181,  181,  271,  293,  271,  273,  314,
      273,  314,  275,  320,  275,  320,  341,  340,  275,  291,
      275,  276,  277,  339,  338,  277,  277,  276,  277,  337,
      335,  277,  277,  275,  281,  275,  281,  283,  322,  283,
      322,  334,  276,  277,  333,  278,  277,  277,  316,  323,
      316,  323,  324,  287,  324,  287,  332,  317,  277,  331,
      318,  277,  277,  290,  290,  290,  292,  292,  292,  330,
      336,  249,  336,  345,  251,  345,  314,  329,  314,  293,

      316,  320,  316,  320,  328,  322,  316,  322,  316,  317,
      277,  327,  326,  277,  277,  317,  277,  325,  321,  277,
      277,  323,  324,  323,  324,  291,  346,  354,  346,  354,
      355,  356,  355,  356,  313,  347,  277,  310,  348,  277,
      277,  316,  336,  316,  336,  362,  368,  362,  368,  309,
      317,  277,  308,  318,  277,  277,  345,  346,  345,  346,
      370,  307,  370,  346,  306,  346,  347,  277,  305,  304,
      277,  277,  347,  277,  303,  302,  277,  277,  346,  371,
      346,  371,  372,  373,  372,  373,  301,  347,  277,  298,
      348,  277,  277,  354,  355,  354,  355,  356,  375,  356,

      375,  378,  362,  378,  362,  380,  368,  380,  368,  370,
      371,  370,  371,  372,  373,  372,  373,  375,  386,  375,
      386,  387,  378,  387,  378,  380,  389,  380,  389,  390,
      393,  390,  393,  386,  387,  386,  387,  389,  390,  389,
      390,  393,  397,  393,  397,  398,  399,  398,  399,  397,
      398,  397,  398,  399,  297,  399,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   46,   46,   46,   46,   46,   46,   46,   46,

       46,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   76,   76,  296,
       76,   76,  295,   76,   76,   76,   77,   77,  294,   77,
       77,   77,   77,   77,   77,  124,  251,  249,  289,  124,
      288,  124,  128,  286,  285,  284,  128,  282,  128,  130,
      130,  280,  130,  130,  130,  130,  130,  130,  132,  132,
      274,  132,  132,  132,  132,  132,  132,  133,  133,  272,
      133,  133,  133,  133,  133,  133,  134,  134,  270,  134,

      134,  134,  134,  134,  134,  159,  269,  265,  264,  159,
      160,  263,  262,  261,  160,  182,  182,  260,  257,  182,
      182,  256,  182,  197,  255,  254,  197,  197,  253,  197,
      201,  253,  251,  201,  201,  249,  201,  203,  203,  247,
      203,  203,  203,  203,  203,  203,  237,  237,  245,  244,
      237,  237,  237,  237,  248,  248,  248,  243,  248,  248,
      248,  248,  250,  250,  250,  242,  250,  250,  250,  250,
      279,  241,  240,  239,  279,  279,  279,  279,  315,  232,
      231,  228,  315,  315,  227,  315,  319,  226,  222,  206,
      319,  319,  319,  319,  349,  161,  192,  191,  349,  349,

      349,  349,  190,  189,  188,  187,  186,  185,  184,  183,
      177,  176,  175,  174,  173,  172,  171,  170,  169,  168,
      167,  164,  161,  152,  151,  150,  149,  148,  147,  146,
      145,  144,  141,  140,  139,  138,  137,  122,  121,  117,
      116,  115,  114,  111,  108,  107,  106,  105,  136,  135,
      131,  129,  122,  121,  117,  116,  115,  111,  108,  107,
      106,  105,   89,   86,  400,   73,   73,   51,   50,   50,
       47,   47,   39,   39,   33,   33,   31,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,

      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400
    } ;

static const flex_int16_t yy_chk[1023] =
    {   0,
        0,    6,    6,    6,    7,    8,  425,   11,   12,   11,
       12,  413,    7,    8,   11,   12,   13,   14,   17,   13,
       14,   13,   14,   18,    0,    0,   17,   34,   34,   34,
      392,   18,   22,   38,   22,   38,   39,   42,   39,   42,
       47,   59,   47,   27,   27,   28,   28,   57,   60,   59,
       22,   60,   57,   22,   22,   22,   22,   22,   22,   22,
      110,  110,   22,   22,   50,   68,   50,   68,   22,   22,
      391,   22,   22,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   50,
       64,   64,   67,   69,   67,   69,   74,   74,   74,   64,

       97,   67,   69,   77,   78,   77,   78,   95,   97,   87,
      211,   87,   95,  122,  122,  211,   23,   23,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   87,  102,  102,  120,  121,  123,
      124,  123,  124,  388,  102,  121,  259,  259,  123,  124,
      125,  120,  125,  131,  161,  131,  161,  163,  169,  163,
      169,   24,   24,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,  126,
      127,  126,  127,  128,  136,  128,  136,  384,  126,  127,
      383,  136,  128,  159,  165,  159,  165,  170,  379,  170,

      159,  165,  159,  270,  270,  159,   25,   25,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,  160,  171,  160,  171,  175,  374,
      175,  160,  178,  160,  178,  180,  160,  180,  183,  191,
      183,  191,  369,  367,  179,  179,  179,  202,  205,  202,
      205,   26,   26,   52,  179,   52,  366,  179,  179,  193,
      195,  193,  195,  198,  365,  198,  193,  195,  193,  195,
      198,   52,  198,  363,   52,   52,   52,   52,   52,   52,
       52,  360,  359,   52,   52,  222,  223,  222,  223,   52,
       52,  357,   52,   52,  148,  148,  148,  218,  218,  224,

      225,  224,  225,  148,  148,  344,  218,  148,  148,  166,
      196,  166,  196,  227,  197,  227,  197,  196,  229,  196,
      229,  197,  196,  197,  342,  232,  197,  232,  341,  340,
      166,  166,  166,  166,  166,  166,  166,  339,  338,  166,
      166,  233,  238,  233,  238,  166,  166,  335,  166,  166,
      167,  167,  167,  234,  240,  234,  240,  334,  333,  167,
      167,  332,  234,  167,  167,  182,  182,  182,  244,  246,
      244,  246,  331,  327,  182,  182,  326,  182,  182,  182,
      200,  201,  200,  201,  252,  325,  252,  200,  201,  200,
      201,  321,  200,  201,  230,  312,  230,  249,  249,  249,

      235,  311,  235,  230,  230,  249,  230,  230,  230,  235,
      236,  236,  236,  251,  251,  251,  253,  310,  253,  236,
      236,  251,  236,  236,  236,  271,  251,  271,  273,  274,
      273,  274,  275,  280,  275,  280,  309,  308,  276,  249,
      276,  275,  275,  307,  306,  275,  275,  276,  276,  305,
      303,  276,  276,  278,  281,  278,  281,  283,  284,  283,
      284,  302,  278,  278,  301,  278,  278,  278,  279,  285,
      279,  285,  286,  287,  286,  287,  300,  279,  279,  299,
      279,  279,  279,  290,  290,  290,  292,  292,  292,  298,
      304,  290,  304,  313,  292,  313,  314,  297,  314,  292,

      316,  320,  316,  320,  296,  322,  317,  322,  317,  316,
      316,  295,  289,  316,  316,  317,  317,  288,  282,  317,
      317,  323,  324,  323,  324,  290,  315,  328,  315,  328,
      329,  330,  329,  330,  272,  315,  315,  269,  315,  315,
      315,  318,  336,  318,  336,  337,  343,  337,  343,  268,
      318,  318,  267,  318,  318,  318,  345,  346,  345,  346,
      350,  266,  350,  347,  265,  347,  346,  346,  264,  263,
      346,  346,  347,  347,  262,  261,  347,  347,  348,  351,
      348,  351,  352,  353,  352,  353,  260,  348,  348,  258,
      348,  348,  348,  354,  355,  354,  355,  356,  358,  356,

      358,  361,  362,  361,  362,  364,  368,  364,  368,  370,
      371,  370,  371,  372,  373,  372,  373,  375,  376,  375,
      376,  377,  378,  377,  378,  380,  381,  380,  381,  382,
      385,  382,  385,  386,  387,  386,  387,  389,  390,  389,
      390,  393,  394,  393,  394,  395,  396,  395,  396,  397,
      398,  397,  398,  399,  257,  399,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  405,  405,  405,  405,  405,  405,  405,  405,

      405,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      407,  407,  407,  407,  407,  407,  407,  407,  407,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  410,  410,  256,
      410,  410,  255,  410,  410,  410,  411,  411,  254,  411,
      411,  411,  411,  411,  411,  412,  250,  248,  247,  412,
      245,  412,  414,  243,  242,  241,  414,  239,  414,  415,
      415,  231,  415,  415,  415,  415,  415,  415,  416,  416,
      228,  416,  416,  416,  416,  416,  416,  417,  417,  226,
      417,  417,  417,  417,  417,  417,  418,  418,  220,  418,

      418,  418,  418,  418,  418,  419,  219,  217,  216,  419,
      420,  215,  214,  213,  420,  421,  421,  212,  210,  421,
      421,  209,  421,  422,  208,  206,  422,  422,  204,  422,
      423,  203,  199,  423,  423,  194,  423,  424,  424,  192,
      424,  424,  424,  424,  424,  424,  426,  426,  190,  189,
      426,  426,  426,  426,  427,  427,  427,  188,  427,  427,
      427,  427,  428,  428,  428,  187,  428,  428,  428,  428,
      429,  186,  185,  184,  429,  429,  429,  429,  430,  177,
      176,  174,  430,  430,  173,  430,  431,  172,  168,  164,
      431,  431,  431,  431,  432,  162,  158,  157,  432,  432,

      432,  432,  156,  155,  154,  153,  152,  151,  150,  149,
      147,  146,  145,  144,  143,  142,  141,  140,  139,  138,
      137,  135,  130,  119,  118,  117,  116,  115,  114,  113,
      112,  111,  109,  108,  107,  106,  105,  104,  103,  101,
      100,   99,   98,   96,   94,   93,   92,   91,   89,   88,
       79,   73,   66,   65,   63,   62,   61,   58,   56,   55,
       54,   53,   51,   49,   31,   30,   29,   21,   20,   19,
       16,   15,   10,    9,    4,    3,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,

      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "main.l"
#line 2 "main.l"
	#include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
	int no_of_comments = 0; 
	int no_of_lines = 0; 
	int no_of_blank_lines = 0;
	int no_of_macros = 0;
    int no_of_variables = 0;
    int no_of_func_dec = 0;
    int no_of_func_def = 0;
    int count=0;
    FILE *temp;
#line 819 "lex.yy.c"
 
#line 821 "lex.yy.c"

#define INITIAL 0
#define count_lines 1
#define count_blank 2
#define count_comment 3
#define count_comment_initial 4
#define remove_string 5
#define remove_string_found 6
#define remove_comment 7
#define remove_comment_found 8
#define count_macro 9
#define count_variable 10
#define count_func_def 11
#define count_func_dec 12
#define func_found 13
#define in_comment 14

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 21 "main.l"


#line 1058 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 401 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 977 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 23 "main.l"
{fwrite( yytext, (size_t) yyleng, 1, temp );BEGIN(in_comment);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 24 "main.l"
{fwrite( yytext, (size_t) yyleng, 1, temp );BEGIN(remove_string);}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 25 "main.l"
{fwrite( yytext, (size_t) yyleng, 1, temp );}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 26 "main.l"
{fwrite( yytext, (size_t) yyleng, 1, temp );}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 27 "main.l"
{BEGIN(remove_string_found);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 28 "main.l"
{BEGIN(remove_string);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 29 "main.l"
;
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 30 "main.l"
{fwrite( yytext, (size_t) yyleng, 1, temp );}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 31 "main.l"
{fwrite( yytext, (size_t) yyleng, 1, temp );}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 33 "main.l"
{no_of_lines++;}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 35 "main.l"
{no_of_blank_lines++;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 37 "main.l"
{BEGIN(count_comment);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 38 "main.l"
;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 39 "main.l"
;
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 40 "main.l"
{no_of_comments++;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 41 "main.l"
BEGIN(count_comment);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 42 "main.l"
{no_of_comments++;BEGIN(count_comment_initial);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 43 "main.l"
{no_of_comments++;BEGIN(count_comment_initial);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 44 "main.l"
{no_of_comments++;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 46 "main.l"
{BEGIN(remove_comment_found);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 47 "main.l"
{BEGIN(remove_comment);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 48 "main.l"
;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 49 "main.l"
;
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 50 "main.l"
{fwrite( yytext, (size_t) yyleng, 1, temp );}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 52 "main.l"
{no_of_macros++;}
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 54 "main.l"
no_of_variables++;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 55 "main.l"
no_of_variables++;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 56 "main.l"
no_of_variables++;
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 58 "main.l"
{no_of_func_def++;BEGIN(func_found);count= 1;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 59 "main.l"
count++;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 60 "main.l"
{count--; if(count==0) BEGIN(count_func_def);}
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 62 "main.l"
{no_of_func_dec++;}
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 64 "main.l"
;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 65 "main.l"
ECHO;
	YY_BREAK
#line 1297 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(count_lines):
case YY_STATE_EOF(count_blank):
case YY_STATE_EOF(count_comment):
case YY_STATE_EOF(count_comment_initial):
case YY_STATE_EOF(remove_string):
case YY_STATE_EOF(remove_string_found):
case YY_STATE_EOF(remove_comment):
case YY_STATE_EOF(remove_comment_found):
case YY_STATE_EOF(count_macro):
case YY_STATE_EOF(count_variable):
case YY_STATE_EOF(count_func_def):
case YY_STATE_EOF(count_func_dec):
case YY_STATE_EOF(func_found):
case YY_STATE_EOF(in_comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 401 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 401 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 400);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 65 "main.l"


int yywrap(){} 
int main(){ 

    char * original_file="test.c";
	FILE *fp,*out; 

    fp = fopen(original_file,"r");
	yyrestart(fp);
    BEGIN(count_lines);
    yylex(); 
    fclose(fp);

    fp = fopen(original_file,"r");
    yyrestart(fp);
    BEGIN(count_blank);
	yylex(); 
    fclose(fp);

    fp = fopen(original_file,"r");
    temp= fopen("temp_string.c","w"); 
    yyin = fp;
    BEGIN(remove_string);
    yylex(); 
    fclose(fp);
    fclose(temp);

    fp = fopen("temp_string.c","r");
    yyrestart(fp);
    BEGIN(count_comment_initial);
	yylex();

    temp= fopen("temp_comment.c","w"); 
    fp = fopen("temp_string.c","r");
    yyrestart(fp);
    BEGIN(remove_comment);
	yylex();  
    fclose(fp);
    fclose(temp);

    fp = fopen("temp_comment.c","r");
    yyrestart(fp);
    BEGIN(count_macro);
	yylex();  
    fclose(fp);

    fp = fopen("temp_comment.c","r");
    yyrestart(fp);
    BEGIN(count_variable);
	yylex();  
    fclose(fp);

    fp = fopen("temp_comment.c","r");
    yyrestart(fp);
    BEGIN(count_func_def);
	yylex();  
    fclose(fp);

    fp = fopen("temp_comment.c","r");
    yyrestart(fp);
    BEGIN(count_func_dec);
	yylex();  
    fclose(fp);

    remove("temp_comment.c");
    remove("temp_string.c");
    out = fopen("output.txt","w");
	fprintf(out,"\nNumber of comments "
		"in the given input - %d\n", no_of_comments); 
	fprintf(out,"\nNumber of lines "
		"in the given input - %d\n", no_of_lines+1); 
	fprintf(out,"\nNumber of blank lines "
		"in the given input - %d\n", no_of_blank_lines); 
	fprintf(out,"\nNumber of macros "
		"in the given input - %d\n", no_of_macros);
    fprintf(out,"\nNumber of variables "
		"in the given input - %d\n", no_of_variables);  
    fprintf(out,"\nNumber of function definitions "
		"in the given input - %d\n", no_of_func_def);  
    fprintf(out,"\nNumber of function declaration "
		"in the given input - %d\n", no_of_func_dec);
    fclose(out);
	return 0; 
} 
